"""Project configuration"""
TARGET = "Churn"
RAW_DATA_PATH = "data/bank_data.csv"
PROCESSED_DATA_PATH = "data/processed_bank_data.csv"
MODELLING_DATA_PATH = "data/modelling_bank_data.csv"
EDA_PLOT_DIR = "images"
AGE_HIST_PATH = "eda/age_hist.jpg"
CORR_HEATMAP_PATH = "eda/corr_heatmap.jpg"
